package com.salt.boilerplate.infrastructure.db.schema;

import com.salt.boilerplate.domain.admin.model.Admin;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;

@Entity
@Table(name = "Users")
public class UserSchema extends AbstractEntitySchema<Long> {

    @NotBlank
    @Column(length = 20, unique = true)
    private String username;

    @NotBlank
    @Column(nullable = false, length = 40, unique = true)
    private String email;

    @NotBlank
    @Column(nullable = false, length = 64)
    private String password;

    @NotBlank
    @Column(nullable = false, length = 60)
    private String name;

    @NotBlank
    @Column(nullable = false, length = 20)
    protected String role;

    @Column(nullable = false)
    private boolean enabled;

    public UserSchema(Admin admin) {
        this.setId(admin.getId());
        this.username = admin.getUsername();
        this.password = admin.getPassword();
        this.name = admin.getName();
        this.email = admin.getEmail();
        this.role = admin.getRole();
        this.enabled = true;
    }

    public UserSchema() {
        this.enabled = true;
    }

    public UserSchema(Long id, String username, String name, String email, String password) {
        this.setId(id);
        this.name = name;
        this.email = email;
        this.password = password;
        this.username = username;

    }

    public Admin toAdmin() {
        Admin admin = new Admin(
                this.getUsername(),
                this.getPassword(),
                this.getName(),
                this.getEmail()
        );

        admin.setId(this.getId()); // transform the schema id (generated by database) to entity customer id
        return admin;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

}

